export const closingText = {
  he: {
    brand:'שירת הנבל',title:'עוד צעד קטן לקראת האירוע שלכם',subtitle:'עוברים על הפרטים, מאשרים וחותמים — הכול במקום אחד',
    steps:['אימות טלפון','פרטי האירוע וחתימה','השלמת הסגירה'], verifyIntro:'כדי לצפות בהסכם ולחתום יש לאמת את הטלפון שנקבע עבור ההזמנה. קוד חד־פעמי יישלח בוואטסאפ',
    sendCode:'שלח קוד אימות', resendCode:'שלח קוד נוסף',code:'קוד אימות',verify:'אמת והצג את ההסכם',retry:'נסה שוב',version:'גרסה',state:'מצב',
    consents:'אישורים והרשאות',accept:'קראתי ואני מאשר/ת סעיף זה',signature:'חתימה',name:'שם מלא של החותם/ת',role:'תפקיד או קשר לאירוע (רשות)',
    signHelp:'יש לחתום באצבע או בעכבר. עם האישור יישמרו המסמך, החתימה, מועד האימות ותיעוד טכני של הפעולה.',sign:'אני מאשר/ת את ההסכם וחותם/ת',saving:'שומר...',working:'מבצע את הפעולה, נא להמתין…',clear:'נקה חתימה',
    event:'האירוע שלכם',date:'מועד האירוע',total:'מחיר כולל',allInclusiveTotal:'מחיר הכל כלול',paidMilestone:'שולם · השלב הושלם',for:'עבור',summary:'תמצית הצעת המחיר',openQuote:'פתיחת הצעת המחיר המלאה PDF ↗',attached:'מצורפת הגרסה שנבחרה בעת הכנת ההסכם:',vatIncluded:'כולל מע״מ',vatExcluded:'לפני מע״מ',perUnit:'ליחידה',discount:'הנחה הכלולה במחיר',paid:'שולם במועד הכנת ההסכם',balance:'יתרה במועד הכנת ההסכם',terms:'תנאי ההתקשרות',milestones:'אבני הדרך לתשלום',due:'עד',conditions:'הרשאות ותנאי סגירה',regularCap:'תקרת חיובים רגילים',exceptionalCap:'תקרת חיובים חריגים',feeNote:'עמלת הסליקה לפי הסעיף שבהסכם.',notice:'לפני חיוב חריג תישלח הודעה ותינתן אפשרות לתשלום חלופי במשך',days:'ימים לפחות.',noNotice:'לא נקבעה חובת הודעה מקדימה לפני חיוב חריג בהרשאה זו.',closingNeeds:'לסגירת האירוע נדרשת חתימה',cardNeeded:' וכרטיס מאומת',cardWaived:'; המנהל אישר מסלול ללא חובת כרטיס',depositNeeded:' ותשלום מקדמה בסך ',depositWaived:'; המנהל אישר מסלול ללא חובת מקדמה',manualOnly:'חיוב מהכרטיס מתבצע רק בפעולה ידנית של מנהל.',
    doneTitle:'הכול מוכן. האירוע אושר',doneDescription:'ההסכם נחתם וכל הדרישות שנקבעו לסגירת האירוע הושלמו.',doneWhat:'מה הושלם?',doneSigned:'ההסכם נחתם',doneCard:'הכרטיס אומת',doneDeposit:'המקדמה שולמה',pdf:'פתיחת העותק החתום',complete:'השלמת סגירת האירוע',completeDescription:'רק השלבים שנקבעו בהסכם נדרשים להשלמת הסגירה.',stepSigned:'חתימה על ההסכם',stepCard:'אימות כרטיס לתשלום',stepDeposit:'תשלום מקדמה',done:'הושלם',pending:'ממתין לביצוע',cardButton:'שמירת כרטיס בדף מאובטח',depositButton:'תשלום מקדמה בדף מאובטח',notClosed:'הדרישות בהסכם הושלמו, אך סגירת האירוע טרם אושרה במערכת. יש לפנות למנהל לבדיקת מצב האירוע.',refresh:'רענון מצב'
  },
  en: {
    brand:'Shirat Hanevel',title:'One step closer to your event',subtitle:'Review the details, approve and sign in one place',
    steps:['Verify phone','Review and sign','Complete closing'],verifyIntro:'To view and sign the agreement, verify the phone number on your booking. A one-time code will be sent via WhatsApp to',
    sendCode:'Send verification code',resendCode:'Send another code',code:'Verification code',verify:'Verify and view agreement',retry:'Try again',version:'Version',state:'Status',
    consents:'Consents and authorizations',accept:'I have read and agree to this clause',signature:'Signature',name:'Full name of signatory',role:'Role or relationship to the event (optional)',
    signHelp:'Sign with your finger or mouse. The document, signature, verification time and technical record will be saved.',sign:'I accept and sign the agreement',saving:'Saving...',working:'Processing, please wait…',clear:'Clear signature',
    event:'Your event',date:'Event date',total:'Total price',allInclusiveTotal:'All-inclusive price',paidMilestone:'Paid · completed',for:'For',summary:'Quotation summary',openQuote:'Open full quotation PDF ↗',attached:'The selected version attached to this agreement:',vatIncluded:'Including VAT',vatExcluded:'Before VAT',perUnit:'per unit',discount:'Discount included in the price',paid:'Paid when agreement was prepared',balance:'Balance when agreement was prepared',terms:'Terms of engagement',milestones:'Payment milestones',due:'Due',conditions:'Authorizations and closing terms',regularCap:'Regular charge limit',exceptionalCap:'Exceptional charge limit',feeNote:'Processing fees are governed by the clause in this agreement.',notice:'An exceptional charge will be preceded by a notice and an opportunity to pay another way for at least',days:'days.',noNotice:'No advance notice is required for an exceptional charge under this authorization.',closingNeeds:'Closing the event requires a signature',cardNeeded:' and a verified card',cardWaived:'; card not required',depositNeeded:' and a deposit of ',depositWaived:'; deposit not required',manualOnly:'The card is charged only by a manual action of an administrator.',
    doneTitle:'All set. Your event is confirmed',doneDescription:'The agreement is signed and all closing requirements are complete.',doneWhat:'Completed steps',doneSigned:'Agreement signed',doneCard:'Card verified',doneDeposit:'Deposit paid',pdf:'Open signed copy',complete:'Complete event closing',completeDescription:'Only the steps specified in your agreement are required.',stepSigned:'Sign the agreement',stepCard:'Verify a payment card',stepDeposit:'Pay the deposit',done:'Complete',pending:'Pending',cardButton:'Save card on secure page',depositButton:'Pay deposit on secure page',notClosed:'All agreement requirements are complete, but the event has not yet been confirmed in the system. Contact the administrator.',refresh:'Refresh status'
  }
};
export function localizedSnapshot(snapshot, lang) {
  const version = snapshot?.translations?.[lang];
  return version ? {...snapshot,...version,quote_summary:{...snapshot.quote_summary,pricing_note:version.pricing_note??snapshot.quote_summary?.pricing_note}} : snapshot;
}