import React, { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Download, FileDown, Link2, RotateCcw, Share2, Unlink } from "lucide-react";

const labels = { invoice: "חשבונית מס", receipt: "קבלה", invoice_receipt: "חשבונית מס/קבלה", invoice_credit: "חשבונית זיכוי", proforma: "חשבונית עסקה", work_order: "הזמנת עבודה", quote: "הצעת מחיר", delivery_note: "תעודת משלוח" };
const statuses = { open: "פתוח", fully_credited: "זוכה במלואו", partially_credited: "זוכה חלקית", cancelled: "בוטל" };

export default function FinancialDocumentsTable({ documents, eventsById, onDetach, onCredit, onRefreshPdf, onShare, refreshingPdfId }) {
  const [search, setSearch] = useState("");
  const [type, setType] = useState("all");
  const [status, setStatus] = useState("all");
  const filtered = useMemo(() => documents.filter((doc) => {
    const query = search.trim().toLowerCase();
    const eventName = eventsById.get(doc.linked_event_id)?.event_name || "";
    return (type === "all" || doc.document_type === type) && (status === "all" || doc.status === status) && (!query || [doc.document_number, doc.customer_name, eventName].some((value) => String(value || "").toLowerCase().includes(query)));
  }), [documents, eventsById, search, status, type]);
  return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="חיפוש מספר, לקוח או אירוע" /><Select value={type} onValueChange={setType}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">כל סוגי המסמכים</SelectItem>{Object.entries(labels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">כל הסטטוסים</SelectItem>{Object.entries(statuses).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b text-right text-gray-500"><tr><th className="p-3">מספר</th><th className="p-3">סוג</th><th className="p-3">לקוח</th><th className="p-3">אירוע</th><th className="p-3">סכום</th><th className="p-3">סטטוס</th><th className="p-3">פעולות</th></tr></thead><tbody>{filtered.map((doc) => { const pdf = doc.pdf_original_url || doc.pdf_certified_url; const canCredit = ["invoice", "invoice_receipt"].includes(doc.document_type) && doc.invoice4u_id && doc.status === "open"; return <tr key={doc.id} className="border-b"><td className="p-3 font-medium">{doc.document_number || "—"}</td><td className="p-3">{labels[doc.document_type] || doc.document_type}</td><td className="p-3">{doc.customer_name || "—"}</td><td className="p-3">{doc.is_detached_from_event ? "לא משויך" : eventsById.get(doc.linked_event_id)?.event_name || "—"}</td><td className="p-3">{doc.total != null ? `₪${Number(doc.total).toLocaleString()}` : "—"}</td><td className="p-3">{statuses[doc.status] || doc.status}</td><td className="p-3"><div className="flex gap-1">{pdf && <Button asChild variant="ghost" size="icon" title="הורדה"><a href={pdf} target="_blank" rel="noopener noreferrer"><Download className="h-4 w-4" /></a></Button>}{doc.invoice4u_id && <Button variant="ghost" size="icon" title={pdf ? "רענן קישור PDF" : "הפק PDF"} disabled={refreshingPdfId === doc.id} onClick={() => onRefreshPdf(doc)}><FileDown className="h-4 w-4" /></Button>}{pdf && <Button variant="ghost" size="icon" title="שיתוף" onClick={() => onShare(doc)}><Share2 className="h-4 w-4" /></Button>}{canCredit && <Button variant="ghost" size="icon" title="ביטול מסמך (זיכוי + קבלה שלילית)" onClick={() => onCredit(doc)}><RotateCcw className="h-4 w-4" /></Button>}{doc.linked_event_id && !doc.is_detached_from_event && <Button variant="ghost" size="icon" title="נתק מאירוע" onClick={() => onDetach(doc)}><Unlink className="h-4 w-4" /></Button>}{doc.is_detached_from_event && <Link2 className="m-2 h-4 w-4 text-gray-400" />}</div></td></tr>; })}</tbody></table>{filtered.length === 0 && <p className="p-8 text-center text-gray-500">לא נמצאו מסמכים לפי הסינון שנבחר.</p>}</div></div>;
}