import React,{useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {agreementAction,agreementError} from '@/lib/agreementApi';
import {rebalanceMilestones} from '@/components/billing/rebalanceMilestones';
const input='mt-1 w-full rounded-lg border border-input bg-background p-2 text-foreground disabled:opacity-60';
export default function MilestoneScheduleEditor({agreementId,open,onClose,onSaved}){
 const [preview,setPreview]=useState(null),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!open)return;let active=true;setPreview(null);setError('');agreementAction('milestones_preview',{agreementId}).then(p=>{if(active){setPreview(p);setRows(p.rows);}}).catch(e=>{if(active)setError(agreementError(e));});return()=>{active=false;};},[open,agreementId]);
 const money=n=>new Intl.NumberFormat('he-IL',{style:'currency',currency:preview?.currency||'ILS'}).format(n);
 const changeAmount=(i,value)=>{const amount=Number(value);if(!Number.isFinite(amount))return;const next=rebalanceMilestones(rows,i,amount);const cumulative=next.reduce((s,m,j)=>{if(j<=i)s+=Number(m.amount);return s;},0);const floor=Math.min(preview.totalPaid,preview.rows[i].cumulative_amount);setRows(next);if(cumulative+0.005<floor){setError('הסכום המצטבר באבן הדרך לא יכול להיות נמוך מהסכום שכבר שולם עבורה: '+money(floor));return;}if(cumulative>preview.rows[i].cumulative_amount+0.005){setError('לא ניתן להגדיל תשלום מוקדם; ניתן רק לגלגל סכומים לאבני דרך מאוחרות יותר.');return;}setError('');};
 const save=async()=>{setBusy(true);setError('');try{await agreementAction('milestones',{agreementId,sourceHash:preview.sourceHash,rows:rows.map(m=>({id:m.id,amount:m.amount,due_date:m.due_date}))});await onSaved();onClose();}catch(e){setError(agreementError(e));}finally{setBusy(false);}};
 return <Dialog open={open} onOpenChange={value=>{if(!value&&!busy)onClose();}}><DialogContent dir="rtl" className="max-h-[90dvh] overflow-y-auto bg-card text-card-foreground"><DialogHeader><DialogTitle>עריכת אבני דרך קיימות</DialogTitle><DialogDescription>ניתן להפחית תשלום מוקדם ולגלגל את ההפרש קדימה, או לדחות מועד. אין שינוי במחיר הכולל ואין צורך בחתימה חדשה.</DialogDescription></DialogHeader>{!preview&&!error&&<p role="status">טוען אבני דרך ותשלומים…</p>}{preview&&<><p className="text-sm">כבר שולם באירוע: <strong>{money(preview.totalPaid)}</strong> · סך ההסכם: {money(preview.total)}</p>{rows.map((m,i)=>{const previous=rows.slice(0,i).reduce((s,r)=>s+Number(r.amount),0);const minimum=Math.max(0,Math.min(preview.totalPaid,preview.rows[i].cumulative_amount)-previous);return <fieldset key={m.id} className="rounded-lg border border-border p-3 space-y-2"><legend className="px-1 text-sm font-medium">{m.label}</legend><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><label className="text-sm">סכום<input aria-label={'סכום אבן דרך '+(i+1)} type="number" min={minimum} max={Math.max(0,preview.rows[i].cumulative_amount-previous)} step="0.01" disabled={busy||i===rows.length-1||preview.rows[i].cumulative_amount<=preview.totalPaid} className={input} value={m.amount} onChange={e=>changeAmount(i,e.target.value)}/></label><label className="text-sm">מועד אחרון<input aria-label={'מועד אבן דרך '+(i+1)} type="date" min={preview.rows[i].due_date} disabled={busy||preview.rows[i].cumulative_amount<=preview.totalPaid} className={input} value={m.due_date} onChange={e=>{setError('');setRows(rows.map((r,j)=>j===i?{...r,due_date:e.target.value}:r));}}/></label></div><p className="text-xs text-muted-foreground">מצטבר: {money(previous+Number(m.amount))} · מינימום שמוגן לפי תשלומים שנקלטו: {money(minimum)}</p></fieldset>;})}<p className="text-xs text-muted-foreground">ההפרש מועבר אוטומטית לאבן הדרך הבאה. אבן הדרך האחרונה משלימה את היתרה. החתימה, הקישור והתשלומים שכבר נקלטו נשמרים.</p></>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex flex-wrap gap-2"><Button disabled={!preview||busy||!!error} onClick={save}>{busy?'שומר…':'שמור אבני דרך'}</Button><Button variant="outline" disabled={busy} onClick={onClose}>ביטול</Button></div></DialogContent></Dialog>;
}