import React,{useState} from 'react';
import {base44} from '@/api/base44Client';
import {Button} from '@/components/ui/button';
import {quoteRequest} from '@/components/modularQuote/useQuoteActions';
import QuoteShareLinks from '@/components/modularQuote/QuoteShareLinks';
export default function ModularQuoteRow({quote,onEdit,onRefresh}) {
  const [busy,setBusy]=useState('');const [error,setError]=useState('');const [link,setLink]=useState('');const [pdf,setPdf]=useState('');const [confirm,setConfirm]=useState(false);
  async function run(action){setBusy(action);setError('');try{if(action==='delete'){await base44.entities.ModularQuote.delete(quote.id);onRefresh();}if(action==='share')setLink((await quoteRequest({action:'share',id:quote.id})).url);if(action==='pdf'){const r=await base44.functions.invoke('generateManualQuotePdf',{modularQuoteId:quote.id});if(!r.data?.pdf_url)throw new Error(r.data?.error||'הפקת PDF נכשלה');setPdf(r.data.pdf_url);onRefresh();}}catch(e){setError(e.message);}finally{setBusy('');}}
  return <article className="border rounded-xl p-4 space-y-3"><div className="flex flex-wrap justify-between gap-3"><div className="min-w-0"><h3 className="font-medium break-words">{quote.title}</h3><p className="text-xs text-muted-foreground">עודכן: {new Date(quote.updated_date).toLocaleDateString('he-IL')} · {quote.content?.show_prices===false?'ללא מחירים':'עם מחירים'}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={!!busy} onClick={onEdit}>עריכה</Button><Button size="sm" variant="outline" disabled={!!busy} onClick={()=>run('pdf')}>{busy==='pdf'?'מפיק…':'PDF'}</Button><Button size="sm" variant="outline" disabled={!!busy} onClick={()=>run('share')}>קישור</Button><Button size="sm" variant="ghost" disabled={!!busy} onClick={()=>setConfirm(!confirm)}>מחיקה</Button></div></div>{confirm&&<div className="flex flex-wrap items-center gap-2 text-sm"><span>למחוק את ההצעה והקישור שלה?</span><Button size="sm" variant="destructive" disabled={!!busy} onClick={()=>run('delete')}>אשר מחיקה</Button><Button size="sm" variant="ghost" onClick={()=>setConfirm(false)}>ביטול</Button></div>}{error&&<p role="alert" className="text-destructive text-sm">{error}</p>}<QuoteShareLinks link={link} pdf={pdf}/></article>;
}