import React from 'react';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Button} from '@/components/ui/button';
import QuoteTextSection from '@/components/modularQuote/QuoteTextSection';
import CatalogAdder from '@/components/modularQuote/CatalogAdder';
import QuoteItemsList from '@/components/modularQuote/QuoteItemsList';
import {addOrderedItem} from '@/components/modularQuote/quoteDefaults';
import {GripVertical} from 'lucide-react';
export default function QuoteItemEditor({item,onChange,onRemove,onMove,index,total,services,child=false,dragHandleProps}) {
  const field=(key,value)=>onChange({...item,[key]:value});
  const prefix=`item-${item.id}`;
  return <div className="border rounded-xl p-3 sm:p-4 space-y-3 bg-card text-card-foreground"><div className="flex flex-wrap justify-between items-center gap-2"><div className="flex items-center gap-2"><button type="button" {...dragHandleProps} aria-label={`גרור לסידור ${item.name}`} className="p-2 cursor-grab active:cursor-grabbing text-muted-foreground rounded-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><GripVertical className="h-5 w-5"/></button><strong>{item.kind==='package'?'חבילה':'שירות'}</strong></div><div className="flex gap-1">{onMove&&<><Button variant="ghost" size="sm" disabled={index===0} aria-label={`העלה ${item.name}`} onClick={()=>onMove(-1)}>למעלה</Button><Button variant="ghost" size="sm" disabled={index===total-1} aria-label={`הורד ${item.name}`} onClick={()=>onMove(1)}>למטה</Button></>}<Button variant="ghost" size="sm" onClick={onRemove} aria-label={`הסר ${item.name}`}>הסר</Button></div></div><div><Label htmlFor={`${prefix}-name`}>שם {item.kind==='package'?'החבילה':'השירות'}</Label><Input id={`${prefix}-name`} value={item.name} onChange={e=>field('name',e.target.value)}/></div><div className="grid grid-cols-2 gap-3"><div><Label htmlFor={`${prefix}-qty`}>כמות</Label><Input id={`${prefix}-qty`} type="number" min="0" value={item.quantity} onChange={e=>field('quantity',e.target.value)}/></div>{!child&&<div><Label htmlFor={`${prefix}-price`}>מחיר ליחידה / חבילה (₪)</Label><Input id={`${prefix}-price`} type="number" min="0" step="0.01" value={item.price} onChange={e=>field('price',e.target.value)}/></div>}</div><div className="flex flex-wrap gap-3 text-sm">{[['visible','כלול בהצעה'],['show_quantity','הצג כמות'],['show_description','הצג תיאור'],...(!child?[['show_price','הצג מחיר'],['includes_vat','מחיר כולל מע״מ']]:[])].map(([key,label])=><label key={key} className="flex items-center gap-2 min-h-9"><input type="checkbox" aria-label={`${label}: ${item.name}`} checked={!!item[key]} onChange={e=>field(key,e.target.checked)}/>{label}</label>)}</div><QuoteTextSection label="תיאור" value={item.description} onChange={v=>field('description',v)}/>{item.kind==='package'&&<div className="space-y-3 border-t pt-3"><h4 className="text-sm font-medium">שירותים הכלולים בחבילה</h4><QuoteItemsList items={item.children||[]} listId={`package:${item.id}`} services={services} child onChange={(children,manual=false)=>onChange({...item,children,...(manual?{manual_order:true}:{})})}/><CatalogAdder services={services} childrenOnly onAdd={s=>field('children',addOrderedItem(item.children||[],s,item.manual_order))}/></div>}</div>;
}